version: '3'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root2020!
    ports:
      - 5432:5432
    volumes:
      - /c/PostgreSQL/db:/var/lib/postgresql/data
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_DB_HOST: postgres
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - app-network

  labs-backend:
    build:
      context: ./backend/src
      dockerfile: dockerfile
    container_name: labs-backend
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 5000:80
    depends_on:
      - postgres
    networks:
      - app-network

  # labs-frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: dockerfile
  #   container_name: labs-frontend
  #   ports:
  #     - "80:80"
  #   networks:
  #     - app-network
  #   depends_on:
  #     - postgres
  #     - labs-backend

networks: 
    app-network:
      driver: bridge