FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine AS build-env

# Copy csproj and restore as distinct layers
WORKDIR /src
COPY Labs.sln ./
COPY Labs.Shared/*.csproj ./Labs.Shared/
COPY Labs.Domain/*.csproj ./Labs.Domain/
COPY Labs.Infra/*.csproj ./Labs.Infra/
COPY Labs.Api/*.csproj ./Labs.Api/
RUN dotnet restore

# Copy everything else and build
COPY . ./
WORKDIR /src/Labs.Shared
RUN dotnet build -c Release -o /app

WORKDIR /src/Labs.Domain
RUN dotnet build -c Release -o /app

WORKDIR /src/Labs.Infra
RUN dotnet build -c Release -o /app

WORKDIR /src/Labs.Api
RUN dotnet build -c Release -o /app

WORKDIR /app
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-alpine
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "Labs.Api.dll"]